'''{r}
install.packages("pacman")
pacman::p_load(pacman,party,psych,rio,tidyverse)
library(tidyselect)
library(pacman)
library(rio)
library(party)
library(readxl)

#Importing data from excel
getwd()
f<-file.choose()
gCred <- read_excel(f)
gCred <- read_excel("German_Credit.xls")
View(gCred)

#Exploring the various variables from dataset

summary(gCred)

head(gCred)

names(gCred)

dim(gCred)

str(gCred)



#converting to categorical variables

gCred$`OBS#` <- as.factor(gCred$`OBS#`)
gCred$CHK_ACCT <- as.factor(gCred$CHK_ACCT)
gCred$HISTORY <- as.factor(gCred$HISTORY)
gCred$NEW_CAR <- as.factor(gCred$NEW_CAR)
gCred$USED_CAR <- as.factor(gCred$USED_CAR)
gCred$FURNITURE <- as.factor(gCred$FURNITURE)
gCred$`RADIO/TV` <- as.factor(gCred$`RADIO/TV`)
gCred$EDUCATION <- as.factor(gCred$EDUCATION)
gCred$RETRAINING <- as.factor(gCred$RETRAINING)
gCred$SAV_ACCT <- as.factor(gCred$SAV_ACCT)
gCred$EMPLOYMENT <- as.factor(gCred$EMPLOYMENT)
gCred$MALE_DIV <- as.factor(gCred$MALE_DIV)
gCred$MALE_SINGLE <- as.factor(gCred$MALE_SINGLE)
gCred$MALE_MAR_or_WID <- as.factor(gCred$MALE_MAR_or_WID)
gCred$`CO-APPLICANT` <- as.factor(gCred$`CO-APPLICANT`)
gCred$GUARANTOR <- as.factor(gCred$GUARANTOR)
gCred$PRESENT_RESIDENT <- as.factor(gCred$PRESENT_RESIDENT)
gCred$REAL_ESTATE <- as.factor(gCred$REAL_ESTATE)
gCred$PROP_UNKN_NONE <- as.factor(gCred$PROP_UNKN_NONE)
gCred$OTHER_INSTALL <- as.factor(gCred$OTHER_INSTALL)
gCred$RENT <- as.factor(gCred$RENT)
gCred$OWN_RES <- as.factor(gCred$OWN_RES)
gCred$JOB <- as.factor(gCred$JOB)
gCred$TELEPHONE <- as.factor(gCred$TELEPHONE)
gCred$FOREIGN <- as.factor(gCred$FOREIGN)
gCred$RESPONSE <- as.factor(gCred$RESPONSE)

#standard deviations

sd(gCred$DURATION)
sd(gCred$AMOUNT)
sd(gCred$INSTALL_RATE)
sd(gCred$AGE)
sd(gCred$NUM_CREDITS)
sd(gCred$NUM_DEPENDENTS)
   
mean(gCred$DURATION)   
mean(gCred$AMOUNT)
mean(gCred$INSTALL_RATE)
mean(gCred$AGE)
mean(gCred$NUM_CREDITS)

#Converting good and bad cases

gCred$RESPONSE <- as.factor(ifelse(gCred$RESPONSE == 1, "Good" , "Bad"))
tbl <- table(gCred$RESPONSE)
tbl_pct <- cbind(tbl,round(prop.table(tbl)*100,2))
colnames(tbl_pct)<- c('Count','Percentage')
knitr::kable(tbl_pct)

library (dplyr)

by_group <- gCred %>% group_by(AGE)

by_group

gCred %>% group_by(AGE) %>% summarize(mean_age = mean(AGE))
%>%
  ggplot (aes(x=cyl, y =mean_age)) + geom_bar(stat =)



summary(gCred)

ggplot(ae)

summa


attach(gCred)
plot(RESPONSE, AGE, main="Age vs Response",
     xlab="Age ", ylab="Response", pch=19)


attach(gCred)
plot(RESPONSE, CHK_ACCT, main="CHK_ACCT vs Response",
     xlab="Response ", ylab="CHK_ACCT", pch=19)


attach(gCred)
plot(count($CHK_ACCT), CHK_ACCT, main="CHK_ACCT vs Response",
     xlab="Response ", ylab="CHK_ACCT", pch=19)


attach(gCred)
plot(RESPONSE, AGE, main="Age vs Response",
     xlab="Age ", ylab="Response", pch=19)


attach(gCred)
plot(PURPOSE, AGE, main="Age vs Response",
     xlab="Age ", ylab="Response", pch=19)

attach(gCred)
summary(Duration.of.Credit.Month) 
boxplot(Duration.of.Credit.Month., bty="n",xlab = "Credit Month", cex=0.4)


CrossTable(RESPONSE, , digits=1, prop.r=F, prop.t=F, prop.chisq=F, chisq=T)



### Plotting the graphs##########

p<-ggplot(data=gCred, aes(x=JOB, y=RESPONSE, fill=RESPONSE)) +
  geom_bar(stat="identity")
p

p1<-ggplot(data=gCred, aes(x=CHK_ACCT, y=RESPONSE, fill=RESPONSE)) +
  geom_bar(stat="identity")
p1

p2<-ggplot(data=gCred, aes(x=HISTORY, y=RESPONSE, fill=RESPONSE)) +
  geom_bar(stat="identity")
p2

p3<-ggplot(data=gCred, aes(x=SAV_ACCT, y=RESPONSE, fill=RESPONSE)) +
  geom_bar(stat="identity")
p3

p4<-ggplot(data=gCred, aes(y=EMPLOYMENT, x=RESPONSE, fill=EMPLOYMENT)) +
  geom_bar(stat="identity")
p4

p5<-ggplot(data=gCred, aes(x=PRESENT_RESIDENT, y=RESPONSE, fill=RESPONSE)) +
  geom_bar(stat="identity")
p5





gCred %>%
  mutate(DV_1 = coalesce($NEW_CAR,$USED_CAR,$FURNITURE,$RADIO/TV,
                         $EDUCATION,$RETRAINING))


ggplot(data = gCred, aes(x = , y = rooms)) +
  geom_boxplot()



gCred %>% mutate(POC = cbind)



gCred [,which(colnames(gCred) %in% c("NEW_CAR","USED_CAR","FURNITURE","RADIO/TV","EDUCATION","RETRAINING"))]


gCred %>% gather(gCred(NEW_CAR,USED_CAR))


library(dplyr)
gCred %>%
  mutate(Purpose_of_Credit = case_when(NEW_CAR =  ~ New_Car, USED_CAR = 1 ~ USED_CAR))


gCred %>% 
  mutate(POC = )




plot(y=good[,7],x=good[,8],pch=1,
     xlab="duration",ylab="credit amount",main="")
points(y=bad[,7],x=bad[,8],pch=3,
       xlab="duration",ylab="credit amount",main="")



      #remove the first column

gCred_new$purpose <- as.factor(ifelse
                               ((gCred_new$NEW_CAR|
                                   gCred_new$FURNITURE|
                                   gCred_new$USED_CAR|
                                   gCred_new$RADIO.TV|
                                   gCred_new$EDUCATION|
                                   gCred_new$RETRAINING) == 1, "Credit_granted" , "No_credit_granted"))


gCred_new$purpose <- as.factor(ifelse((gCred_new$)))\









newdat = newdat[,-25]
newdat = as.matrix(newdat[order(newdat$good), ])
siz = c(300,700)
n = round(0.7*siz)

#################################Kaggle#################

gCred = gCred[,-1]

miss = function(x){sum(is.na(x))/length(x)*100}
apply(gCred,2,miss)


#####good vs bad plot####
good = gCred[which(gCred[,32]=='Good'),]
bad = gCred[which(gCred[,32]=="Bad"),]
bad
g <- good[,1]
g

g <- as.numeric(g)
plot(gCred[,32])

####data exploring###
library(ggplot2)
par(mfrow =c(1,3))

hist(as.numeric(unlist(good[,23])),xlab="age",ylab="",main="Good Credit Vs Age",ylim=c(0,160))
hist(as.numeric(unlist(bad[,23])),xlab="age",ylab="",main="Bad Credit Vs Age",ylim=c(0,160))

hist(as.numeric(unlist(gCred[,23])),xlab="age",ylab="",main="Response vs Age")

##fetch column number for Real estate##
colnames(gCred) #Colnames will return column names present in the dataset,gCred=DataFrame name
data.frame(colnames(gCred)) #Returns column index numbers in table format,gCred=DataFrame name

## Histogram plots for Real estate variable##
library(ggplot2)
par(mfrow =c(1,3))
hist(as.numeric(unlist(good[,21])),xlab="Real Estate",ylab="",main="Good Credit Vs Real Estate",ylim=c(0,500))
hist(as.numeric(unlist(bad[,21])),xlab="Rental_Property",ylab="",main="Bad Credit Vs Real Estate",ylim=c(0,500))

hist(as.numeric(unlist(gCred[,21])),xlab="age",ylab="",main="Credit vs Real Estate")

####################Amount vs Credit Duration #####
library(ggplot2)
par(mfrow =c(1,1))
plot(y=as.numeric(unlist(good[,11])),
    x=as.numeric(unlist(good[,3])),pch=1,
    xlab="Duration(months)",ylab="credit amount",main="Good Credit vs Duration")
points(y=as.numeric(unlist(bad[,11])),
x=as.numeric(unlist(bad[,3])),pch=3,
xlab="Duration (months)",ylab="credit amount",main="")
        
plot(y=as.numeric(unlist(bad[,11])),
    x=as.numeric(unlist(bad[,3])),pch=3,
    xlab="Duration",ylab="credit amount",main="Bad Credit vs Duration")
        
        
## The number of short term loans are greater than the long term loans
## Short term loans(<30 months) with higher Credit amount(>10,000) have Bad Credit Response

        
#####Categorical Variable Analysis Jitesh##
install.packages("corrplot")
library("corrplot")
library("dplyr")
install.packages("apaTables")
library(apaTables)
gCred$CHK_ACCT <- as.numeric(gCred$CHK_ACCT)
gCred$HISTORY <- as.numeric(gCred$HISTORY)
gCred$SAV_ACCT <- as.numeric(gCred$SAV_ACCT)
gCred$EMPLOYMENT <- as.numeric(gCred$EMPLOYMENT)
gCred$PRESENT_RESIDENT <- as.numeric(gCred$PRESENT_RESIDENT)
gCred$JOB <- as.numeric(gCred$JOB)
gCred$RESPONSE <- as.numeric(gCred$RESPONSE)

df1 <- gCred %>% select(c(CHK_ACCT,HISTORY,SAV_ACCT,EMPLOYMENT,PRESENT_RESIDENT,JOB,RESPONSE))

df1

df.cor = cor(df1)
corPlot(df.cor)
corPlot(df.cor)

apa.cor.table(df1,"APA correlation Table.doc")


```
